{{- $sa := mergeOverwrite (deepCopy .Values.serviceAccount) (dict "create" true) }}
{{- if $sa.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flask-app-chart.serviceAccountName" . }}
  labels:
    {{- include "flask-app-chart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
